function customer(){
	var strVar="";
	strVar += "<div class=\"cusDiv\">";
	strVar += "";
	strVar += "		<div>";
	strVar += "			<h2>Add Customer<\/h2>";
	strVar += "		<\/div>";
	strVar += "		<input type=\"text\" id=cusId>";
	strVar += "		<div>";
	strVar += "			<label>Customer Name*:<\/label>";
	strVar += "		<\/div>";
	strVar += "		<div>";
	strVar += "			<input type=text id=\"cusname\" placeholder=\"Name\">";
	strVar += "		<\/div>";
	strVar += "		";
	strVar += "		<div>";
	strVar += "			<label>Address*:<\/label>";
	strVar += "		<\/div>";
	strVar += "		<div>";
	strVar += "			<input type=text id=\"addr\" placeholder=\"Address\">";
	strVar += "		<\/div>";
	strVar += "		<div>";
	strVar += "			<label>Contact Number*:<\/label>";
	strVar += "		<\/div>";
	strVar += "		<div>";
	strVar += "			<input type=text id=\"conno\" placeholder=\"Mobile Number\">";
	strVar += "		<\/div>";
	strVar += "		<div>";
	strVar += "			<input type=submit value=\"Add\" id=\"add\">";
	strVar += "			<input type=submit value=\"Update\" id=\"update\">";
	strVar += "		<\/div>";
	strVar += "";
	strVar += "	<\/div>";
	strVar += "	<div class=\"getAllCus\"><\/div>";
$('.fin')[0].innerHTML = strVar;
}
function account(){
	var acc="";
	acc += "<div class=account><\/div>";
	acc += "<div>";
	acc += "<h3>AddAccounts<\/h3>";
	acc += "<\/div>";
	acc += "<div> ";
	acc += "<label>Account Id:<\/label>";
	acc += "<\/div>";
	acc += "<div>";
	acc += "<input type=text id=acc>";
	acc += "<\/div>";
	acc += "<div> ";
	acc += "<label>Line:<\/label> ";
	acc += "<\/div>";
	acc += "<div>";
	acc += "<input type=\"text\" id=line>";
	acc += "<\/div>";
	acc += "<div>";
	acc += "<label>Collection Type:<\/label>";
	acc += "<\/div>";
	acc += "<div>";
	acc += "<input type=text id=colltype>";
	acc += "<\/div>";
	acc += "<div>";
	acc += "<label>Amount Given:<\/label>";
	acc += "<\/div>";
	acc += "<div>";
	acc += "<input type=text id=amtgiven placeholder=\"Amount Given\">";
	acc += "<\/div>";
	acc += "<div>";
	acc += "<label>Amount To Pay:<\/label>";
	acc += "<\/div>";
	acc += "<div>";
	acc += "<input type=text id=amttopay placeholder=\"Amount To Pay\">";
	acc += "<\/div>";
	acc += "<div> ";
	acc += "<label>Customer Id:<\/label> ";
	acc += "<\/div>";
	acc += "<div>";
	acc += "<input type=text id=cusId placeholder=\"customer Id\">";
	acc += "<\/div>";
	acc += "<div>";
	acc += "<input type=submit value=Add id=sub>";
	acc += "<input type=submit value=Update id=update>";
	acc += "<\/div>";
	acc += "<div class=getAllAccount><\/div>";
$('.fin')[0].innerHTML = acc;
}
function payment(){
	var pay="";
	pay += "<div class=pay>";
	pay += "<div>";
	pay += "<h3>AddPayment<\/h3>";
	pay += "<\/div>";
	pay += "<input type=text id=payId>";
	pay += "<div> ";
	pay += "<label>Account Number:<\/label> ";
	pay += "<\/div>";
	pay += "<div>";
	pay += "<input type=\"text\" id=\"accId\" placeholder=\"Account Number\">";
	pay += "<\/div>";
	pay += "<div>";
	pay += "<label>Amount:<\/label>";
	pay += "<\/div>";
	pay += "<div>";
	pay += "<input type=\"text\" id=\"amount\" placeholder=\"Paid Amount\">";
	pay += "<\/div>";
	pay += "<div>";
	pay += "<label>Date:<\/label>";
	pay += "<\/div>";
	pay += "<div>";
	pay += "<input type=\"text\" id=\"date\" placeholder=\"04-07-1991\">";
	pay += "<\/div>";
	pay += "<div>";
	pay += "<input type=\"submit\" value=\"add\" id=\"addpay\">";
	pay += "<input type=\"submit\" value=\"update\" id=\"updatepay\">";
	pay += "<\/div>";
	pay += "<\/div>";
	pay += "<div class=\"getAllPayment\"><\/div>";
$('.fin')[0].innerHTML = pay;
}
function statement(){
	var sta="";
	sta += "<div>";
	sta += "<label>AccountNumber:<\/label>";
	sta += "<\/div>";
	sta += "<div>";
	sta += "<input type=text id=accId placeholder=\"Account Number\">";
	sta += "<\/div>";
	sta += "<h4 id=name><\/h4>";
	sta += "<h4 id=bal><\/h4>";
	sta += "<div class=getStatement><\/div>";
	sta += "<input type=button id=print value=Print onclick=previewStatement()>";
$('.fin')[0].innerHTML = sta;
}